spring.application.name=portfolio

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=julianacomparoto@gmail.com
spring.mail.password=ilda clfe ufxs yirv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true