spring.application.name=portfolio

server.port=${PORT:8080}

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:myemail@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:mypassword}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

